### PR TITLE
Themes

### PR DESCRIPTION
**Pull request by gib-bowden**

### CODE REVIEW

**Comment by harringtonben** [comment]
👍

**Comment by DreRandaci** [comment]
👍

**Review by lewiskg — COMMENTED** [review]
In domhandler.js, don't we still need the .reverse() method on line 9 and 23?

**Comment by gib-bowden** [comment]
@lewiskg I changed the way a message is added from push to unshift - so an added messages goes to index zero now - line 18 in messages.js

**Pull request merged**
